name: tweech
description: A very powerful real-time live-streaming application that enables share of screen,  and recording.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.1.0
  provider: ^6.0.4
  dotted_border: ^2.0.0+2
  file_picker: ^4.5.1
  agora_rtc_engine: ^5.0.1
  permission_handler: ^9.2.0
  uuid: ^3.0.6
  http: ^0.13.4
  timeago:
  lottie:
  cached_network_image: ^3.2.0
  flutter_native_splash: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/icon.png"
    background_color: "#fff"
    theme_color: "#fff"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

dependency_overrides:
  firebase_core_platform_interface: 4.5.1


flutter:

  uses-material-design: true

  assets:
    - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
